
export const CAREGIVER = 'Caregiver'
export const GUARDIAN = 'Guardian'
export const CONTACT = 'Contact'
export const CHILD = 'Child'
export const ATTENDANCE = 'Attendance'
export const PAYMENTS = 'Payments'
export const FINANCES = 'Finances'
export const QUESTIONS = 'Questions'
export const ACCOUNTS = 'Accounts'