
export const CAREGIVER = 'Caregiver'
export const GUARDIANS = 'Guardians'
export const CONTACTS = 'Contacts'
export const CHILDREN = 'Children'
export const ATTENDANCE = 'Attendance'
export const FINANCES = 'Finances'
export const EXPENSES = 'Expenses'
export const PAYMENTS = 'Payments'
export const QUESTIONS = 'Questions'
export const ACCOUNTS = 'Accounts'